sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js

node_js:
  - "7"

branches:
  only:
    - master

before_install:
  - npm install gulp -g

script:
  - npm install

cache:
  directories:
  - node_modules

notifications:
  email:
    - jwcnewton@gmail.com